# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2


_PROTOCOLSIGNATURE_SIGNATUREALGORITHM = descriptor.EnumDescriptor(
  name='SignatureAlgorithm',
  full_name='protocol.ProtocolSignature.SignatureAlgorithm',
  filename='SignatureAlgorithm',
  values=[
    descriptor.EnumValueDescriptor(
      name='SHA1_RSA', index=0, number=1,
      options=None,
      type=None),
  ],
  options=None,
)

_PROTOCOLSIGNERINFO_HASHALGORITHM = descriptor.EnumDescriptor(
  name='HashAlgorithm',
  full_name='protocol.ProtocolSignerInfo.HashAlgorithm',
  filename='HashAlgorithm',
  values=[
    descriptor.EnumValueDescriptor(
      name='SHA256', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SHA512', index=1, number=2,
      options=None,
      type=None),
  ],
  options=None,
)


_PROTOCOLWAVELETDELTA = descriptor.Descriptor(
  name='ProtocolWaveletDelta',
  full_name='protocol.ProtocolWaveletDelta',
  filename='common.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='hashed_version', full_name='protocol.ProtocolWaveletDelta.hashed_version', index=0,
      number=1, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='author', full_name='protocol.ProtocolWaveletDelta.author', index=1,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='operation', full_name='protocol.ProtocolWaveletDelta.operation', index=2,
      number=3, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='address_path', full_name='protocol.ProtocolWaveletDelta.address_path', index=3,
      number=4, type=9, cpp_type=9, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_PROTOCOLHASHEDVERSION = descriptor.Descriptor(
  name='ProtocolHashedVersion',
  full_name='protocol.ProtocolHashedVersion',
  filename='common.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='version', full_name='protocol.ProtocolHashedVersion.version', index=0,
      number=1, type=3, cpp_type=2, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='history_hash', full_name='protocol.ProtocolHashedVersion.history_hash', index=1,
      number=2, type=12, cpp_type=9, label=2,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_PROTOCOLWAVELETOPERATION_MUTATEDOCUMENT = descriptor.Descriptor(
  name='MutateDocument',
  full_name='protocol.ProtocolWaveletOperation.MutateDocument',
  filename='common.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='document_id', full_name='protocol.ProtocolWaveletOperation.MutateDocument.document_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='document_operation', full_name='protocol.ProtocolWaveletOperation.MutateDocument.document_operation', index=1,
      number=2, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_PROTOCOLWAVELETOPERATION = descriptor.Descriptor(
  name='ProtocolWaveletOperation',
  full_name='protocol.ProtocolWaveletOperation',
  filename='common.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='add_participant', full_name='protocol.ProtocolWaveletOperation.add_participant', index=0,
      number=1, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='remove_participant', full_name='protocol.ProtocolWaveletOperation.remove_participant', index=1,
      number=2, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='mutate_document', full_name='protocol.ProtocolWaveletOperation.mutate_document', index=2,
      number=3, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='no_op', full_name='protocol.ProtocolWaveletOperation.no_op', index=3,
      number=4, type=8, cpp_type=7, label=1,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_PROTOCOLDOCUMENTOPERATION_COMPONENT_KEYVALUEPAIR = descriptor.Descriptor(
  name='KeyValuePair',
  full_name='protocol.ProtocolDocumentOperation.Component.KeyValuePair',
  filename='common.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='key', full_name='protocol.ProtocolDocumentOperation.Component.KeyValuePair.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='protocol.ProtocolDocumentOperation.Component.KeyValuePair.value', index=1,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_PROTOCOLDOCUMENTOPERATION_COMPONENT_KEYVALUEUPDATE = descriptor.Descriptor(
  name='KeyValueUpdate',
  full_name='protocol.ProtocolDocumentOperation.Component.KeyValueUpdate',
  filename='common.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='key', full_name='protocol.ProtocolDocumentOperation.Component.KeyValueUpdate.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='old_value', full_name='protocol.ProtocolDocumentOperation.Component.KeyValueUpdate.old_value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='new_value', full_name='protocol.ProtocolDocumentOperation.Component.KeyValueUpdate.new_value', index=2,
      number=3, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_PROTOCOLDOCUMENTOPERATION_COMPONENT_ELEMENTSTART = descriptor.Descriptor(
  name='ElementStart',
  full_name='protocol.ProtocolDocumentOperation.Component.ElementStart',
  filename='common.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='protocol.ProtocolDocumentOperation.Component.ElementStart.type', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='attribute', full_name='protocol.ProtocolDocumentOperation.Component.ElementStart.attribute', index=1,
      number=2, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_PROTOCOLDOCUMENTOPERATION_COMPONENT_REPLACEATTRIBUTES = descriptor.Descriptor(
  name='ReplaceAttributes',
  full_name='protocol.ProtocolDocumentOperation.Component.ReplaceAttributes',
  filename='common.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='empty', full_name='protocol.ProtocolDocumentOperation.Component.ReplaceAttributes.empty', index=0,
      number=1, type=8, cpp_type=7, label=1,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='old_attribute', full_name='protocol.ProtocolDocumentOperation.Component.ReplaceAttributes.old_attribute', index=1,
      number=2, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='new_attribute', full_name='protocol.ProtocolDocumentOperation.Component.ReplaceAttributes.new_attribute', index=2,
      number=3, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_PROTOCOLDOCUMENTOPERATION_COMPONENT_UPDATEATTRIBUTES = descriptor.Descriptor(
  name='UpdateAttributes',
  full_name='protocol.ProtocolDocumentOperation.Component.UpdateAttributes',
  filename='common.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='empty', full_name='protocol.ProtocolDocumentOperation.Component.UpdateAttributes.empty', index=0,
      number=1, type=8, cpp_type=7, label=1,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='attribute_update', full_name='protocol.ProtocolDocumentOperation.Component.UpdateAttributes.attribute_update', index=1,
      number=2, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_PROTOCOLDOCUMENTOPERATION_COMPONENT_ANNOTATIONBOUNDARY = descriptor.Descriptor(
  name='AnnotationBoundary',
  full_name='protocol.ProtocolDocumentOperation.Component.AnnotationBoundary',
  filename='common.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='empty', full_name='protocol.ProtocolDocumentOperation.Component.AnnotationBoundary.empty', index=0,
      number=1, type=8, cpp_type=7, label=1,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='end', full_name='protocol.ProtocolDocumentOperation.Component.AnnotationBoundary.end', index=1,
      number=2, type=9, cpp_type=9, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='change', full_name='protocol.ProtocolDocumentOperation.Component.AnnotationBoundary.change', index=2,
      number=3, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_PROTOCOLDOCUMENTOPERATION_COMPONENT = descriptor.Descriptor(
  name='Component',
  full_name='protocol.ProtocolDocumentOperation.Component',
  filename='common.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='annotation_boundary', full_name='protocol.ProtocolDocumentOperation.Component.annotation_boundary', index=0,
      number=1, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='characters', full_name='protocol.ProtocolDocumentOperation.Component.characters', index=1,
      number=2, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='element_start', full_name='protocol.ProtocolDocumentOperation.Component.element_start', index=2,
      number=3, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='element_end', full_name='protocol.ProtocolDocumentOperation.Component.element_end', index=3,
      number=4, type=8, cpp_type=7, label=1,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='retain_item_count', full_name='protocol.ProtocolDocumentOperation.Component.retain_item_count', index=4,
      number=5, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='delete_characters', full_name='protocol.ProtocolDocumentOperation.Component.delete_characters', index=5,
      number=6, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='delete_element_start', full_name='protocol.ProtocolDocumentOperation.Component.delete_element_start', index=6,
      number=7, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='delete_element_end', full_name='protocol.ProtocolDocumentOperation.Component.delete_element_end', index=7,
      number=8, type=8, cpp_type=7, label=1,
      default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='replace_attributes', full_name='protocol.ProtocolDocumentOperation.Component.replace_attributes', index=8,
      number=9, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='update_attributes', full_name='protocol.ProtocolDocumentOperation.Component.update_attributes', index=9,
      number=10, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_PROTOCOLDOCUMENTOPERATION = descriptor.Descriptor(
  name='ProtocolDocumentOperation',
  full_name='protocol.ProtocolDocumentOperation',
  filename='common.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='component', full_name='protocol.ProtocolDocumentOperation.component', index=0,
      number=1, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_PROTOCOLAPPLIEDWAVELETDELTA = descriptor.Descriptor(
  name='ProtocolAppliedWaveletDelta',
  full_name='protocol.ProtocolAppliedWaveletDelta',
  filename='common.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='signed_original_delta', full_name='protocol.ProtocolAppliedWaveletDelta.signed_original_delta', index=0,
      number=1, type=11, cpp_type=10, label=2,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='hashed_version_applied_at', full_name='protocol.ProtocolAppliedWaveletDelta.hashed_version_applied_at', index=1,
      number=2, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='operations_applied', full_name='protocol.ProtocolAppliedWaveletDelta.operations_applied', index=2,
      number=3, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='application_timestamp', full_name='protocol.ProtocolAppliedWaveletDelta.application_timestamp', index=3,
      number=4, type=3, cpp_type=2, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_PROTOCOLSIGNEDDELTA = descriptor.Descriptor(
  name='ProtocolSignedDelta',
  full_name='protocol.ProtocolSignedDelta',
  filename='common.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='delta', full_name='protocol.ProtocolSignedDelta.delta', index=0,
      number=1, type=12, cpp_type=9, label=2,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='signature', full_name='protocol.ProtocolSignedDelta.signature', index=1,
      number=2, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_PROTOCOLSIGNATURE = descriptor.Descriptor(
  name='ProtocolSignature',
  full_name='protocol.ProtocolSignature',
  filename='common.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='signature_bytes', full_name='protocol.ProtocolSignature.signature_bytes', index=0,
      number=1, type=12, cpp_type=9, label=2,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='signer_id', full_name='protocol.ProtocolSignature.signer_id', index=1,
      number=2, type=12, cpp_type=9, label=2,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='signature_algorithm', full_name='protocol.ProtocolSignature.signature_algorithm', index=2,
      number=3, type=14, cpp_type=8, label=2,
      default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
    _PROTOCOLSIGNATURE_SIGNATUREALGORITHM,
  ],
  options=None)


_PROTOCOLSIGNERINFO = descriptor.Descriptor(
  name='ProtocolSignerInfo',
  full_name='protocol.ProtocolSignerInfo',
  filename='common.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='hash_algorithm', full_name='protocol.ProtocolSignerInfo.hash_algorithm', index=0,
      number=1, type=14, cpp_type=8, label=2,
      default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='domain', full_name='protocol.ProtocolSignerInfo.domain', index=1,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='certificate', full_name='protocol.ProtocolSignerInfo.certificate', index=2,
      number=3, type=12, cpp_type=9, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
    _PROTOCOLSIGNERINFO_HASHALGORITHM,
  ],
  options=None)


_PROTOCOLWAVELETDELTA.fields_by_name['hashed_version'].message_type = _PROTOCOLHASHEDVERSION
_PROTOCOLWAVELETDELTA.fields_by_name['operation'].message_type = _PROTOCOLWAVELETOPERATION
_PROTOCOLWAVELETOPERATION_MUTATEDOCUMENT.fields_by_name['document_operation'].message_type = _PROTOCOLDOCUMENTOPERATION
_PROTOCOLWAVELETOPERATION.fields_by_name['mutate_document'].message_type = _PROTOCOLWAVELETOPERATION_MUTATEDOCUMENT
_PROTOCOLDOCUMENTOPERATION_COMPONENT_ELEMENTSTART.fields_by_name['attribute'].message_type = _PROTOCOLDOCUMENTOPERATION_COMPONENT_KEYVALUEPAIR
_PROTOCOLDOCUMENTOPERATION_COMPONENT_REPLACEATTRIBUTES.fields_by_name['old_attribute'].message_type = _PROTOCOLDOCUMENTOPERATION_COMPONENT_KEYVALUEPAIR
_PROTOCOLDOCUMENTOPERATION_COMPONENT_REPLACEATTRIBUTES.fields_by_name['new_attribute'].message_type = _PROTOCOLDOCUMENTOPERATION_COMPONENT_KEYVALUEPAIR
_PROTOCOLDOCUMENTOPERATION_COMPONENT_UPDATEATTRIBUTES.fields_by_name['attribute_update'].message_type = _PROTOCOLDOCUMENTOPERATION_COMPONENT_KEYVALUEUPDATE
_PROTOCOLDOCUMENTOPERATION_COMPONENT_ANNOTATIONBOUNDARY.fields_by_name['change'].message_type = _PROTOCOLDOCUMENTOPERATION_COMPONENT_KEYVALUEUPDATE
_PROTOCOLDOCUMENTOPERATION_COMPONENT.fields_by_name['annotation_boundary'].message_type = _PROTOCOLDOCUMENTOPERATION_COMPONENT_ANNOTATIONBOUNDARY
_PROTOCOLDOCUMENTOPERATION_COMPONENT.fields_by_name['element_start'].message_type = _PROTOCOLDOCUMENTOPERATION_COMPONENT_ELEMENTSTART
_PROTOCOLDOCUMENTOPERATION_COMPONENT.fields_by_name['delete_element_start'].message_type = _PROTOCOLDOCUMENTOPERATION_COMPONENT_ELEMENTSTART
_PROTOCOLDOCUMENTOPERATION_COMPONENT.fields_by_name['replace_attributes'].message_type = _PROTOCOLDOCUMENTOPERATION_COMPONENT_REPLACEATTRIBUTES
_PROTOCOLDOCUMENTOPERATION_COMPONENT.fields_by_name['update_attributes'].message_type = _PROTOCOLDOCUMENTOPERATION_COMPONENT_UPDATEATTRIBUTES
_PROTOCOLDOCUMENTOPERATION.fields_by_name['component'].message_type = _PROTOCOLDOCUMENTOPERATION_COMPONENT
_PROTOCOLAPPLIEDWAVELETDELTA.fields_by_name['signed_original_delta'].message_type = _PROTOCOLSIGNEDDELTA
_PROTOCOLAPPLIEDWAVELETDELTA.fields_by_name['hashed_version_applied_at'].message_type = _PROTOCOLHASHEDVERSION
_PROTOCOLSIGNEDDELTA.fields_by_name['signature'].message_type = _PROTOCOLSIGNATURE
_PROTOCOLSIGNATURE.fields_by_name['signature_algorithm'].enum_type = _PROTOCOLSIGNATURE_SIGNATUREALGORITHM
_PROTOCOLSIGNERINFO.fields_by_name['hash_algorithm'].enum_type = _PROTOCOLSIGNERINFO_HASHALGORITHM

class ProtocolWaveletDelta(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PROTOCOLWAVELETDELTA

class ProtocolHashedVersion(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PROTOCOLHASHEDVERSION

class ProtocolWaveletOperation(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class MutateDocument(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _PROTOCOLWAVELETOPERATION_MUTATEDOCUMENT
  DESCRIPTOR = _PROTOCOLWAVELETOPERATION

class ProtocolDocumentOperation(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class Component(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    
    class KeyValuePair(message.Message):
      __metaclass__ = reflection.GeneratedProtocolMessageType
      DESCRIPTOR = _PROTOCOLDOCUMENTOPERATION_COMPONENT_KEYVALUEPAIR
    
    class KeyValueUpdate(message.Message):
      __metaclass__ = reflection.GeneratedProtocolMessageType
      DESCRIPTOR = _PROTOCOLDOCUMENTOPERATION_COMPONENT_KEYVALUEUPDATE
    
    class ElementStart(message.Message):
      __metaclass__ = reflection.GeneratedProtocolMessageType
      DESCRIPTOR = _PROTOCOLDOCUMENTOPERATION_COMPONENT_ELEMENTSTART
    
    class ReplaceAttributes(message.Message):
      __metaclass__ = reflection.GeneratedProtocolMessageType
      DESCRIPTOR = _PROTOCOLDOCUMENTOPERATION_COMPONENT_REPLACEATTRIBUTES
    
    class UpdateAttributes(message.Message):
      __metaclass__ = reflection.GeneratedProtocolMessageType
      DESCRIPTOR = _PROTOCOLDOCUMENTOPERATION_COMPONENT_UPDATEATTRIBUTES
    
    class AnnotationBoundary(message.Message):
      __metaclass__ = reflection.GeneratedProtocolMessageType
      DESCRIPTOR = _PROTOCOLDOCUMENTOPERATION_COMPONENT_ANNOTATIONBOUNDARY
    DESCRIPTOR = _PROTOCOLDOCUMENTOPERATION_COMPONENT
  DESCRIPTOR = _PROTOCOLDOCUMENTOPERATION

class ProtocolAppliedWaveletDelta(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PROTOCOLAPPLIEDWAVELETDELTA

class ProtocolSignedDelta(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PROTOCOLSIGNEDDELTA

class ProtocolSignature(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PROTOCOLSIGNATURE

class ProtocolSignerInfo(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PROTOCOLSIGNERINFO

